#ifndef RAINBOW_DETAIL_CPPFEATURES_HPP_INCLUDED
#define RAINBOW_DETAIL_CPPFEATURES_HPP_INCLUDED

#if defined(__cpp_concepts) and __cpp_concepts >= 201907
#define RAINBOW_HAS_CONCEPTS
#endif

#endif RAINBOW_DETAIL_CPPFEATURES_HPP_INCLUDED
